{"stability":{"unstable":"ðŸ”¬ This is a nightly-only experimental API.  (try_from #33417)"},"apiName":"std::num::TryFromIntError","apiType":"struct","apiDocumentation":{"apiDescription":["The error type returned when a checked integral type conversion fails."]},"trait implementations":[{"name":"impl std::clone::Clone for std::num::TryFromIntError","stable since":"1.0.0"},{"name":"impl std::fmt::Debug for std::num::TryFromIntError","stable since":"1.0.0"},{"name":"impl std::cmp::Eq for std::num::TryFromIntError","stable since":"1.0.0"},{"name":"impl std::cmp::PartialEq<std::num::TryFromIntError> for std::num::TryFromIntError","stable since":"1.0.0"},{"name":"impl std::convert::From<!> for std::num::TryFromIntError","stable since":"1.0.0"},{"name":"impl std::marker::Copy for std::num::TryFromIntError","stable since":"1.0.0"},{"name":"impl std::fmt::Display for std::num::TryFromIntError","stable since":"1.0.0"},{"name":"impl std::error::Error for std::num::TryFromIntError","stable since":"1.0.0"},{"name":"impl std::marker::Send for std::num::TryFromIntError","stable since":"1.0.0"},{"name":"impl std::marker::Sync for std::num::TryFromIntError","stable since":"1.0.0"}]}