{"stability":{"stable since":"1.26.0"},"apiName":"std::thread::AccessError","apiType":"struct","apiDocumentation":{"apiDescription":["An error returned by LocalKey::try_with."]},"trait implementations":[{"name":"impl std::fmt::Debug for std::thread::AccessError","stable since":"1.0.0"},{"name":"impl std::fmt::Display for std::thread::AccessError","stable since":"1.0.0"},{"name":"impl std::marker::Send for std::thread::AccessError","stable since":"1.0.0"},{"name":"impl std::marker::Sync for std::thread::AccessError","stable since":"1.0.0"}]}