{"create_time":"2025-04-05T09:36:52.540Z","id":"1bf06095-ee7d-4197-a9ca-62dc3b08a4ef","source_url":"file:///C:/Users/Dj/.rustup/toolchains/1.30-x86_64-pc-windows-msvc/share/doc/rust/html/std/io/enum.ErrorKind.html","previous_url":"D:\\Lessons\\projects\\rustKG\\rustkg_be\\sandbox\\exams\\effective\\output\\zero-shot-with-rules\\std_io-enum_ErrorKind\\merged_299c4751-4d58-44ce-b63e-384b8da094da.json","relations":["has attribute","has method","implements trait","stable since version"],"delete_triples":[{"triples":[["std::io::Cursor","has description","A `Cursor` wraps another type and provides it with a `Seek` implementation."]],"startIndex":24346,"endIndex":64129},{"triples":[],"startIndex":30329,"endIndex":68137}],"add_triples":[{"triples":[["std::io::Cursor","has description","A `Cursor` wraps an in-memory buffer and provides it with a `Seek` implementation."],["std::io::ErrorKind","has attribute","non_exhaustive"],["std::io::ErrorKind::NotFound","has description","An entity was not found, often a file."],["std::io::ErrorKind::PermissionDenied","has description","The operation lacked the necessary privileges to complete."],["std::io::ErrorKind::ConnectionRefused","has description","The connection was refused by the remote server."],["std::io::ErrorKind::ConnectionReset","has description","The connection was reset by the remote server."],["std::io::ErrorKind::ConnectionAborted","has description","The connection was aborted (terminated) by the remote server."],["std::io::ErrorKind::NotConnected","has description","The network operation failed because it was not connected yet."],["std::io::ErrorKind::AddrInUse","has description","A socket address could not be bound because the address is already in use elsewhere."],["std::io::ErrorKind::AddrNotAvailable","has description","A nonexistent interface was requested or the requested address was not local."],["std::io::ErrorKind::BrokenPipe","has description","The operation failed because a pipe was closed."],["std::io::ErrorKind::AlreadyExists","has description","An entity already exists, often a file."],["std::io::ErrorKind::WouldBlock","has description","The operation needs to block to complete, but the blocking operation was requested to not occur."],["std::io::ErrorKind::InvalidInput","has description","A parameter was incorrect."],["std::io::ErrorKind::InvalidData","has description","Data not valid for the operation were encountered. Unlike InvalidInput, this typically means that the operation parameters were valid, however the error was caused by malformed input data. For example, a function that reads a file into a string will error with InvalidData if the file's contents are not valid UTF-8."],["std::io::ErrorKind::TimedOut","has description","The I/O operation's timeout expired, causing it to be canceled."],["std::io::ErrorKind::WriteZero","has description","An error returned when an operation could not be completed because a call to `write` returned `Ok(0)`."],["std::io::ErrorKind::Interrupted","has description","This operation was interrupted. Interrupted operations can typically be retried."],["std::io::ErrorKind::Other","has description","Any I/O error not part of this list."],["std::io::ErrorKind::UnexpectedEof","has description","An error returned when an operation could not be completed because an \"end of file\" was reached prematurely."],["std::io::ErrorKind::UnexpectedEof","stable since version","1.6.0"]],"startIndex":24346,"endIndex":64129},{"triples":[["std::io::ErrorKind","implements trait","std::marker::Send"],["std::io::ErrorKind","implements trait","std::marker::Sync"],["std::io::Error","implements trait","std::convert::From"],["std::io::Error","has method","from"],["std::io::Error::from","has description","Performs the conversion."]],"startIndex":30329,"endIndex":68137}],"metrics":{"escapeCount":0,"costTime":667218,"totalUsage":{"prompt_tokens":38222,"completion_tokens":17702,"cached_tokens":0,"reasoning_tokens":16802},"chunkLength":2,"chunksInfo":[{"chunkIndex":0,"strLength":39783,"costTime":283175},{"chunkIndex":1,"strLength":37808,"costTime":384043}]},"model":"deepseek-r1-250120","extraInfo":{},"changes_info_triples":[["std::io::Cursor","updates description","A `Cursor` wraps an in-memory buffer and provides it with a `Seek` implementation."],["std::io::ErrorKind","adds attribute","non_exhaustive"],["std::io::ErrorKind::NotFound","adds description","An entity was not found, often a file."],["std::io::ErrorKind::PermissionDenied","adds description","The operation lacked the necessary privileges to complete."],["std::io::ErrorKind::ConnectionRefused","adds description","The connection was refused by the remote server."],["std::io::ErrorKind::ConnectionReset","adds description","The connection was reset by the remote server."],["std::io::ErrorKind::ConnectionAborted","adds description","The connection was aborted (terminated) by the remote server."],["std::io::ErrorKind::NotConnected","adds description","The network operation failed because it was not connected yet."],["std::io::ErrorKind::AddrInUse","adds description","A socket address could not be bound because the address is already in use elsewhere."],["std::io::ErrorKind::AddrNotAvailable","adds description","A nonexistent interface was requested or the requested address was not local."],["std::io::ErrorKind::BrokenPipe","adds description","The operation failed because a pipe was closed."],["std::io::ErrorKind::AlreadyExists","adds description","An entity already exists, often a file."],["std::io::ErrorKind::WouldBlock","adds description","The operation needs to block to complete, but the blocking operation was requested to not occur."],["std::io::ErrorKind::InvalidInput","adds description","A parameter was incorrect."],["std::io::ErrorKind::InvalidData","adds description","Data not valid for the operation were encountered. Unlike InvalidInput, this typically means that the operation parameters were valid, however the error was caused by malformed input data. For example, a function that reads a file into a string will error with InvalidData if the file's contents are not valid UTF-8."],["std::io::ErrorKind::TimedOut","adds description","The I/O operation's timeout expired, causing it to be canceled."],["std::io::ErrorKind::WriteZero","adds description","An error returned when an operation could not be completed because a call to `write` returned `Ok(0)`."],["std::io::ErrorKind::Interrupted","adds description","This operation was interrupted. Interrupted operations can typically be retried."],["std::io::ErrorKind::Other","adds description","Any I/O error not part of this list."],["std::io::ErrorKind::UnexpectedEof","adds description","An error returned when an operation could not be completed because an \"end of file\" was reached prematurely."],["std::io::ErrorKind::UnexpectedEof","stable since","1.6.0"],["std::io::ErrorKind","adds feature","std::marker::Send"],["std::io::ErrorKind","adds feature","std::marker::Sync"],["std::io::Error","adds feature","std::convert::From"],["std::io::Error","adds feature","from"],["std::io::Error::from","adds description","Performs the conversion."]]}